### PR TITLE
Create group_RejectCommaSafeNumbersOnlyBeginning.txt

### PR DESCRIPTION
**Pull request by georgd**

### CODE REVIEW

**Comment by fbennett** [comment]
Which (require/reject) is meant to have no affixes? The test has parens on both...

**Comment by fbennett** [comment]
It's okay. Will figure it out.

**Comment by georgd** [comment]
Sorry. The require test should have the affixes. But I just see that this test doesn’t show the issue once the copy/paste error is cleaned up. I'll go back to the style file to find out what is happening.

**Comment by fbennett** [comment]
The other fixes to date are in place and the LRR changes merged, with updates to ``citeproc-test-runner`` and the Jurism beta.

**Pull request merged**
