### PR TITLE
Fix ES5 compatibility breaking because of for..of loops

### PR DESCRIPTION
**Pull request by miguelsm**

### CODE REVIEW

**Comment by dsifford** [comment]
@miguelsm Using for-in is not a direct subsititute of for-of because it includes properties that exist in the prototype chain. 

```js
const x = {foo: 'foo'};

const y = Object.create(x);

y.bar = 'bar';

for (const z in y) {
    console.log(z);
}
```

Above will print `foo` and `bar` to the console.

You can guard against this by checking `y.hasOwnProperty(z)` prior to doing any work, but most would say it's better to just not use for..in for objects because of the confusion and tricky bugs they can create.

@fbennett why not just compile with babel?

**Comment by miguelsm** [comment]
Thanks for pointing that out @dsifford - I used ```for..in``` loops in order to be consistent with this existing code on line 210 on that same file (maybe it was intended to be a ```for..of``` loop as well?):

```javascript
for (var opener in _nestingParams) {
  openers.push(opener);
  vals[_nestingParams[opener].closer] = true;
}
```

I have made another commit using regular ```for``` loops instead.

In my case the environment where I'm trying to run citeproc-js (Google Apps Script) doesn't support Babel's compiled output either because of the use of ```.return()``` as a method name and the use of ```Symbol``` in this plugin: [transform-es2015-for-of](https://babeljs.io/docs/plugins/transform-es2015-for-of/).

I tried changing that plugin to use brackets instead of dot notation for accessing that ```.return()``` method but still Babel polyfill wasn't running out-of-the-box on Google Apps Script either. So I just thought it'd be easier just replacing these ```for..of``` loops on citeproc-js so it's compatible with ES5 (and Google Apps Script's flavour of it) without relying on any external tooling.

**Comment by dsifford** [comment]
@miguelsm Good to know! Wasn't aware of Babel not playing nicely with Google Apps script.

**Comment by fbennett** [comment]
@miguelsm Sorry for the long delay in chiming in on this thread. I'd like to follow up and confirm your requirements. Do I read you correctly as saying that you need for the citeproc-js code to be ES5 out of the box, in order to run the module in the context of Google App Script? Also, is that still the case now (in August...)?

**Comment by miguelsm** [comment]
@fbennett Yes, it'd need to be ES5 out of the box. As of today GAS is [not yet supporting any ES6 feature](https://issuetracker.google.com/issues/36764074). Transpiling with Babel leads to other issues with GAS.

**Comment by fbennett** [comment]
Understood. Thanks.

Frank

**Pull request merged**
